### PR TITLE
[WIP]Update to Kibana 7.10

### PR DESCRIPTION
**Pull request by ch-bas**
Hi @nsano-rururu ,
I saw that you asked for help in order to update this plugin to Kibana's new Platform, so I made the minimum changes in order to make it running in Kibana 7.10.x.
In this PR you can see the plugin appearing in Kibana's.
I'm not sure how the backend works exactly tbh, but I made an example of how to query the '**elasalert**' api in '**server.ts**'.
I hope this may help to make it working perfectly with the backend!

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Thank you very much for this pull request!

**Comment by nsano-rururu** [comment]
@ch-bas

yarn build doesn't work. I think it has been confirmed to work, but can you tell me how it worked?

yarn v1.22.10
Node.js v14.15.4.
npm v7.2.0

```
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ yarn build
yarn run v1.22.4
$ yarn plugin-helpers build
$ node ../kibana/scripts/plugin_helpers build
Kibana does not support the current Node.js version v10.21.0. Please use Node.js v14.15.4.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ nvm use 14.15.4
Now using node v14.15.4 (npm v6.14.10)
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ yarn build
yarn run v1.22.10
$ yarn plugin-helpers build
$ node ../kibana/scripts/plugin_helpers build
Native extraction module not loaded, msgpackr will still run, but with decreased performance. The module '/home/sano/dkwork3/kibana/node_modules/msgpackr-extract/build/Release/msgpackr-extract.node'
Error: The module '/home/sano/dkwork3/kibana/node_modules/lmdb-store/build/Release/lmdb-store.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ npm rebuild
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/sano/dkwork3/elastalert-kibana-plugin/node_modules/@kbn/plugin-helpers/bin/plugin-helpers.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/sano/dkwork3/elastalert-kibana-plugin/node_modules/@kbn/plugin-helpers/bin/plugin-helpers.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sano/.npm/_logs/2021-01-24T12_39_14_608Z-debug.log
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @elastic/safer-lodash-set@link:../elastic-safer-lodash-set (node_modules/@kbn/config/node_modules/@elastic/safer-lodash-set):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../elastic-safer-lodash-set
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/config-schema@link:../kbn-config-schema (node_modules/@kbn/config/node_modules/@kbn/config-schema):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-config-schema
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/logging@link:../kbn-logging (node_modules/@kbn/config/node_modules/@kbn/logging):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-logging
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/std@link:../kbn-std (node_modules/@kbn/config/node_modules/@kbn/std):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-std
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/utils@link:../kbn-utils (node_modules/@kbn/dev-utils/node_modules/@kbn/utils):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-utils
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/std@link:../kbn-std (node_modules/@kbn/logging/node_modules/@kbn/std):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-std
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/i18n@link:../kbn-i18n (node_modules/@kbn/monaco/node_modules/@kbn/i18n):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-i18n
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/babel-preset@link:../kbn-babel-preset (node_modules/@kbn/optimizer/node_modules/@kbn/babel-preset):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-babel-preset
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/config@link:../kbn-config (node_modules/@kbn/optimizer/node_modules/@kbn/config):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-config
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/dev-utils@link:../kbn-dev-utils (node_modules/@kbn/optimizer/node_modules/@kbn/dev-utils):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-dev-utils
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/std@link:../kbn-std (node_modules/@kbn/optimizer/node_modules/@kbn/std):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-std
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/ui-shared-deps@link:../kbn-ui-shared-deps (node_modules/@kbn/optimizer/node_modules/@kbn/ui-shared-deps):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-ui-shared-deps
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/dev-utils@link:../kbn-dev-utils (node_modules/@kbn/plugin-helpers/node_modules/@kbn/dev-utils):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-dev-utils
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/optimizer@link:../kbn-optimizer (node_modules/@kbn/plugin-helpers/node_modules/@kbn/optimizer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-optimizer
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/i18n@link:../kbn-i18n (node_modules/@kbn/ui-shared-deps/node_modules/@kbn/i18n):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-i18n
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/monaco@link:../kbn-monaco (node_modules/@kbn/ui-shared-deps/node_modules/@kbn/monaco):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-monaco
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @kbn/config-schema@link:../kbn-config-schema (node_modules/@kbn/utils/node_modules/@kbn/config-schema):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unsupported URL Type "link:": link:../kbn-config-schema
npm WARN elastalert-kibana-plugin@1.3.0 No repository field.

removed 13 packages in 1.267s
found 0 vulnerabilities

[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ yarn build
yarn run v1.22.10
$ yarn plugin-helpers build
$ node ../kibana/scripts/plugin_helpers build
Native extraction module not loaded, msgpackr will still run, but with decreased performance. The module '/home/sano/dkwork3/kibana/node_modules/msgpackr-extract/build/Release/msgpackr-extract.node'
Error: The module '/home/sano/dkwork3/kibana/node_modules/lmdb-store/build/Release/lmdb-store.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ ls
CONTRIBUTING.md  README.md  common    kibana-elastalert-plugin-showcase.gif  node_modules       package.json  server        tsconfig.json
LICENSE.md       build      index.js  kibana.json                            package-lock.json  public        showcase.gif  yarn.lock
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ ls build/
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ npm -v
6.14.10
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ npm install -g npm@7.2.0
/home/sano/.nvm/versions/node/v14.15.4/bin/npm -> /home/sano/.nvm/versions/node/v14.15.4/lib/node_modules/npm/bin/npm-cli.js
/home/sano/.nvm/versions/node/v14.15.4/bin/npx -> /home/sano/.nvm/versions/node/v14.15.4/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.2.0
added 56 packages from 28 contributors, removed 241 packages and updated 194 packages in 6.999s
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ yarn build
yarn run v1.22.10
$ yarn plugin-helpers build
$ node ../kibana/scripts/plugin_helpers build
Native extraction module not loaded, msgpackr will still run, but with decreased performance. The module '/home/sano/dkwork3/kibana/node_modules/msgpackr-extract/build/Release/msgpackr-extract.node'
Error: The module '/home/sano/dkwork3/kibana/node_modules/lmdb-store/build/Release/lmdb-store.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at Module.Hook._require.Module.require (/home/sano/dkwork3/kibana/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[CORP\sano@a-ngft53r34ong elastalert-kibana-plugin]$ 
```

**Comment by ch-bas** [comment]
You have to use 'nvm', as mentioned [here](https://www.elastic.co/guide/en/kibana/current/development-getting-started.html).
`nvm use`
Then build the plugin using:
`yarn build --kibana-version=7.10.0`.
As a result, you should expect a zip file under the folfer **build**.

**Comment by nsano-rururu** [comment]
@ch-bas 

I ran the command I was instructed to do, but I get an error.
error message 「Error: Cannot find module 'require-in-the-middle'」

```
$ yarn build --kibana-version=7.10.0
yarn run v1.22.10
$ yarn plugin-helpers build --kibana-version=7.10.0
$ node ../kibana/scripts/plugin_helpers build --kibana-version=7.10.0
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'require-in-the-middle'
Require stack:
- /home/sano/dkwork3/kibana/src/setup_node_env/harden/child_process.js
- /home/sano/dkwork3/kibana/src/setup_node_env/harden/index.js
- /home/sano/dkwork3/kibana/src/setup_node_env/no_transpilation.js
- /home/sano/dkwork3/kibana/scripts/plugin_helpers.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/sano/dkwork3/kibana/src/setup_node_env/harden/child_process.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sano/dkwork3/kibana/src/setup_node_env/harden/child_process.js',
    '/home/sano/dkwork3/kibana/src/setup_node_env/harden/index.js',
    '/home/sano/dkwork3/kibana/src/setup_node_env/no_transpilation.js',
    '/home/sano/dkwork3/kibana/scripts/plugin_helpers.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ch-bas** [comment]
@nsano-rururu , 
having that error means that you have a configuration problem.
Kindly follow these steps:
In you main Kibana repository, run:
`yarn cache clean`
Then:
`yarn kbn clean`.
Then install the dependencies with:
`yarn kbn bootstrap`.
Now navigate to your plugins folder( usually under kibana/plugins) and run this command:
`nvm which`
You should expect to see in node version => **10.22.1**.
If you are not able to see the node version, it means you had a problem when installing nvm on your machine.
The last step should be now to build the release with: 
`yarn build --kibana-version=7.10.0`
I hope it's clear now :))

**Comment by nsano-rururu** [comment]
When I wrote the following settings in kibana.yml, an error occurred, so it seems that it is necessary to correct the part related to reading the configuration file, but the contents that you have supported will be merged into the following branch and work will continue. Thank you for your support.
https://github.com/nsano-rururu/elastalert-kibana-plugin/tree/migrating-plugin-new-platform

kibana.yml

```
# elastalert-kibana-plugin
elastalert-kibana-plugin.serverHost: elastalert
elastalert-kibana-plugin.serverPort: 3030
```

**Pull request closed without merging**
